remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

#Site Settings 
locale: "en-US"
title: "Rohit Karmudi"
subtitle: "Research Analyst | Analytics Developer | AI Enthusiast | Part-time Philosopher"
name: "Rohit Karmudi"
description: "Sharing my experience and insights through analytics. (My statistical models predict my comedy career has a low probability of success.)"
url: "https://rohit196.github.io"
logo: "/assets/images/logo.png"
#Site Features
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true
share: true
comments:
  provider: "disqus"
  disqus:
    shortname: "rohitkarmudi"
social-share: true
featured_posts: true

#Site Author
author:
  name: "Rohit Karmudi"
  avatar: "/assets/images/avatar.jpg"
  bio: "Research Analyst | Analytics Developer | AI Enthusiast | Part-time Philosopher"
  location: "Toronto, Canada"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:rohitkarmudi1996@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rohit196"  
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rohit-karmudi/"
  
#Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rohit196"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rohit-karmudi/"
  custom: true


#collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  books:
    output: true
    permalink: /books/:path/


# Defaults - applies settings to specific content types
defaults:
  # _posts (blog)
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages (static pages)
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio (portfolio items)
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  # _books (book items)
  - scope:
      path: ""
      type: books
    values:
      layout: single
      author_profile: true
      share: true
      read_time: false
      related: true
      toc: true
  # assets (custom CSS and JS files)
  - scope:
      path: "assets/css"
      type: "assets"
    values:
      output: true
  - scope:
      path: "assets/js"
      type: "assets"
    values:
      output: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

#Pagination
paginate: 5 #Number of posts per page
paginate_path: "/page:num/" #Pagination path

#Add Necessary Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-toc
  - jekyll-remote-theme

#Additional settings
markdown: kramdown
highlighter : rouge
future: true
timezone: America/Toronto

# Include custom CSS and JS files
include:
  - _pages
  - assets
  - assets/css
  - assets/js

# Ensure output of assets
keep_files:
  - assets
  - assets/css
  - assets/js

# Sass/SCSS settings
sass:
  sass_dir: _sass
  style: compressed

